---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "STADIUM-Py %(asctime)s|%(levelname)s| %(message)s"
    datefmt: '%Y/%m/%d %H:%M:%S'
  testfmt:
    format: "%(asctime)s|%(name)s|%(levelname)s| %(message)s"
    datefmt: '%Y/%m/%d %H:%M:%S'
  errorfmt:
    format: "%(asctime)s|%(levelname)s| %(message)s"
    datefmt: '%Y/%m/%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: errorfmt
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: errorfmt
    filename: results/tmp/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: testfmt
    filename: results/tmp/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]